# NumPy Basics

This section introduces some basics of NumPy, a linear algebra and matrix manipulation library. 

We begin by importing NumPy, which by convention is imported as `np` to save typing:

In [1]:
import numpy as np

## 1-Dimensional Data Structures

First, we will look at 1-dimensional data structures.

In [2]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

This represents the vector $\mathbf{v} \in \mathbb{R}^{10\times 1} = [0 1 2 3 4 5 6 7 8 9]$

You can access elements using 0-based indices:

In [3]:
v[3]

3

Accessing a range of values can be done using the `:` operator

In [4]:
v[0:3]

array([0, 1, 2])

For brevity you can omit the first digit before `:` to mean from the first element. Omitting the index after the `:` means until the last element:

In [5]:
v[:3]

array([0, 1, 2])

Using `-` can be used to select the all elements except the last three for example:

In [6]:
v[:-3]

array([0, 1, 2, 3, 4, 5, 6])

Or select the last three elements:

In [7]:
v[-3:]

array([7, 8, 9])

Leaving the indexes out entirely is equivalent to saying `0:len(v)`

In [8]:
v[0:len(v)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
v[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

A method called array broadcasting can be used to apply an operation to all elements within a list:

In [10]:
v  = v + 1
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2D Arrays (Matrices)
NumPy can handle multidimensional matrics as well as one dimension data structures. When indexing a multi-dimensional array, the main difference is that you index by rows and columns, in that order, and use the comma (`,`) character to seperate the row and column indices.

In [11]:
m = np.arange(9).reshape(3,3)

In [12]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Indexing 2-dimensional arrays

To index 2-dimensional arrays, all we need is the `,` character. You first supply your row index, followed by `,` and you then supply your column index. 

Let's get the first row of the data:

In [13]:
row_index = 0
m[row_index]

array([0, 1, 2])

Let's now get only the second item of the first row:

In [14]:
col_index = 1
m[row_index, col_index]

1

Normally you will not use variables for indexing, here are some examples using integers. 

Let's get the first column of the matrix:

In [15]:
m[:, 0]

array([0, 3, 6])

Again, we use the colon (`:`) character to mean _all elements_: 

In [16]:
m[:,:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Which is nicer than saying something like this:

In [17]:
m[0:np.shape(m)[0], 0:np.shape(m)[1]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Let us retrieve the bottom corner of the matrix:

In [18]:
m[-2:, -2:]

array([[4, 5],
       [7, 8]])

Or the top right:

In [19]:
m[:2, :2]

array([[0, 1],
       [3, 4]])

**Remember, ranges are specified using the colon `:` character. For 2-dimensional arrays, use the comma `,` character to define ranges for rows then columns.**

## Advanced
We can specify repititions using the `::` syntax:

In [20]:
m[:,::2] # All rows, every 2nd column

array([[0, 2],
       [3, 5],
       [6, 8]])

In [21]:
m[::2,::2] # Every 2nd row, every 2nd column

array([[0, 2],
       [6, 8]])

## Element-wise Operations
We mentioned earlier that operations can be performed in one-dimensional lists in an element-wise fashion. The same is true for multi-dimensional data structures. These operations are performed in an optimsed manner and are very efficient.

In [22]:
m**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [23]:
m + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Operations can be performed between 2D and 1D data structures, as long as there is one common length shared between them. The data structure `m` is a $3 \times 3$ matrix, while the data structure `n` is vector of length 3:

In [24]:
n = np.array([1, 2, 3])
n

array([1, 2, 3])

In [25]:
m + n

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [26]:
m * n

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])